### ISSUE TITLE
Webhooks issue

### ISSUE THREAD

**Issue by JayManCanada6014** [kjdElectronics/fd-tone-notify#15]
Hey,

Not sure if your still supporting this or not but Post Recording webhooks no matter what way I try seem to be broken,

Oct-23-2022 17:25:12 error : WebHook URL_REMOVE Failed to upload file (Multipart Form Data). Error: TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer. Received type boolean (false)

N8N does the same thing.

**Comment by kdolan** [comment]
Can you please provide the configuration for the webhook that results in the error?

**Comment by JayManCanada6014** [comment]
> Can you please provide the configuration for the webhook that results in the error?

FDNotify config or what I have setup in n8n to accept the webhook?

BTW it's ok it someone sees the API URL, it's a temp one, and not turned on.

"name": "TEST_PAGES_INTERNAL",
        "tones": [
          450,
          550
        ],
        "matchThreshold": 10,
        "tolerancePercent": 0.02,
        "notifications": {
          "preRecording": {
		"externalCommands": [
              
            ]
          },
          "postRecording": {
			"webhooks": [
                {
                  "address": "N8NURL",
                  "headers": {"custom-header": "value", "from-env-var": "CUSTOM_ENV_VAR_AUTH_HEADER", "note":  "from-env-var set to value of 'AUTH_HEADER' environment var or null if the variable is not set"},
                  "custom": {
                    "anyObject": true
                  }
                }
              ],  
            "externalCommands": [
            
            ]
          }
        }
      },

![image](https://user-images.githubusercontent.com/66147998/197425638-fb4a9775-1803-48e5-811e-ec23271cb1e9.png)

**Comment by kdolan** [comment]
@JayManCanada6014 If my memory serves me correct there is not a feature to get the address of a webhook from an env var. Try adding the URL directly into the config.

**Comment by JayManCanada6014** [comment]
> @JayManCanada6014 If my memory serves me correct there is not a feature to get the address of a webhook from an env var. Try adding the URL directly into the config.

It is right into the config  
"address": "N8NURL",
I just removed the URL so it wasn't public.  

it's also not just my N8N that won't accept the webhook this site for testing webhooks rejects it as well  https://webhook.site/

**Comment by kdolan** [comment]
Can you paste the error message that you get when running `--test-notifications`?
For example, with the config below I get the below error:

Config:
```JSON
                {
                  "address": "http://localhost:8500/endpoint",
                  "headers": {"custom-header": "value", "from-env-var": "CUSTOM_ENV_VAR_AUTH_HEADER", "note":  "from-env-var set to value of 'AUTH_HEADER' environment var or null if the variable is not set"},
                  "custom": {
                    "anyObject": true
                }
```
Error:
```
Oct-24-2022 16:17:13 error : WebHook http://localhost:8500/endpoint Failed. Error: FetchError: request to http://localhost:8500/endpoint failed, reason: connect ECONNREFUSED 127.0.0.1:8500

Oct-24-2022 16:17:13 debug : FetchError: request to http://localhost:8500/endpoint failed, reason: connect ECONNREFUSED 127.0.0.1:8500```

**Comment by JayManCanada6014** [comment]
So with --test-notifications
C:\FDNotify>fd-tone-notify.exe --test-notifications
Oct-24-2022 17:13:51 crit : Push Bullet does not have an API Key. Notifications will not be sent
Oct-24-2022 17:13:51 warning : Secret FD_CORALOGIX_PRIVATE_KEY has not been set or has an empty value
Oct-24-2022 17:13:51 warning : Secret FD_SMTP_USERNAME has not been set or has an empty value
Oct-24-2022 17:13:51 warning : Secret FD_SMTP_PASSWORD has not been set or has an empty value
Oct-24-2022 17:13:51 info : Send TEST Pre Recording Notifications
Oct-24-2022 17:13:51 info : All TEST Pre Recording Notifications Sent for TEST_PAGES_INTERNAL
Oct-24-2022 17:13:51 info : Sending 1x POST Recording webhook notifications.
Oct-24-2022 17:13:51 info : All TEST POST Recording Notifications Sent for TEST_PAGES_INTERNAL

And results on n8n: 
![image](https://user-images.githubusercontent.com/66147998/197631168-69eb11a1-c462-4db3-b68a-40ee2868d169.png)


Running normally
C:\FDNotify>fd-tone-notify.exe
Oct-24-2022 17:14:05 crit : Push Bullet does not have an API Key. Notifications will not be sent
Oct-24-2022 17:14:05 warning : Secret FD_CORALOGIX_PRIVATE_KEY has not been set or has an empty value
Oct-24-2022 17:14:05 warning : Secret FD_SMTP_USERNAME has not been set or has an empty value
Oct-24-2022 17:14:05 warning : Secret FD_SMTP_PASSWORD has not been set or has an empty value
Oct-24-2022 17:14:05 info : Adding Detector for TEST_PAGES_INTERNAL with tones 450Hz, 550Hz. Match Threshold: 10, Tolerance: 2%
Oct-24-2022 17:14:05 info : Mic Instance Has Started
Oct-24-2022 17:14:06 info : Initializing Recording Worker Thread
Oct-24-2022 17:14:16 info : Detector 450Hz ±2% Matches @ 450Hz. Count 8/10
Oct-24-2022 17:14:16 info : Detector 450Hz ±2% Matches @ 450Hz. Count 9/10
Oct-24-2022 17:14:16 info : Detector 450Hz ±2% Matches @ 450Hz. Count 10/10
Oct-24-2022 17:14:18 info : Detector 550Hz ±2% Matches @ 551.25Hz. Count 8/10
Oct-24-2022 17:14:18 info : Detector 550Hz ±2% Matches @ 551.25Hz. Count 9/10
Oct-24-2022 17:14:18 info : Detector 550Hz ±2% Matches @ 551.25Hz. Count 10/10
Oct-24-2022 17:14:18 alert : MULTI TONE MATCH: Detector TEST_PAGES_INTERNAL 450Hz,550Hz Detected. Match Averages: 450Hz, 551.25Hz
Oct-24-2022 17:14:18 info : All notifications for TEST_PAGES_INTERNAL have finished processing
Oct-24-2022 17:14:18 info : Starting Recording 1666646058370.wav
Oct-24-2022 17:14:18 info : Mic Instance Has Started
Oct-24-2022 17:14:33 warning : Fail Safe End Recoding - Max Time Limit Reached
Oct-24-2022 17:14:33 info : Stopping Recording...
Oct-24-2022 17:14:33 alert : Mic Instance Has STOPPED
Oct-24-2022 17:14:33 info : Finished Recording
Oct-24-2022 17:14:33 info : Sending 1x POST Recording webhook notifications.
Oct-24-2022 17:14:33 error : WebHook https://URLREMOVED Failed to upload file (Multipart Form Data). Error: TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer. Received type boolean (false)
Oct-24-2022 17:14:33 error : Webhook Error: https://URLREMOVED
Oct-24-2022 17:14:49 info : Initializing Recording Worker Thread

BTW if you want to email me  renfrewcountyscanner at gmail.    we have talked before.

**Comment by JayManCanada6014** [comment]
Is there anything I can change to fix this entire on FDN or N8N?

**Comment by kdolan** [comment]
I don't think so. From the log it looks like the issue is with it trying to pickup the file for the webhook. I'm guessing the path or something getting passed is incorrect but I hadn't had a chance to look at it yet.

As a workaround you could use either the pre recording web hook (I assume that works) or as a temporary work around while I look into this check out the s3 upload external command example. If you modify that to hit your endpoint it should work

**Comment by JayManCanada6014** [comment]
> I don't think so. From the log it looks like the issue is with it trying to pickup the file for the webhook. I'm guessing the path or something getting passed is incorrect but I hadn't had a chance to look at it yet.
> 
> As a workaround you could use either the pre recording web hook (I assume that works) or as a temporary work around while I look into this check out the s3 upload external command example. If you modify that to hit your endpoint it should work

Pre-Recording does work, I used it when Post-Recording didn't work but I wanted to try having the file attached to the webhook so I started working on post-recording.

**Comment by JayManCanada6014** [comment]
Stupid question.  How do I compile that to a windows .exe?

**Comment by kdolan** [comment]
@JayManCanada6014 I just published a new release. See the binaries and update notes here https://github.com/kjdElectronics/fd-tone-notify/releases/tag/v0.2.0
