### ISSUE TITLE
Sound device IDs

### ISSUE THREAD

**Issue by 737simpilot** [kjdElectronics/fd-tone-notify#20]
I use more than one audio device, Is there a way to find out which audio device ID my devices use? Thanks.

**Comment by kdolan** [comment]
What OS are you using and how you configured Pulse Audio?

**Comment by kdolan** [comment]
You will use the dsnoop device and configure pulse audio for Linux. Windows is limited to the default input device.
https://github.com/kjdElectronics/fd-tone-notify#Linux-and-Raspberry-Pi
