### ISSUE TITLE
Allow Discord Support For Webhooks

### ISSUE THREAD

**Issue by zigsphere** [kjdElectronics/fd-tone-notify#22]
I added a Discord webhook URL to the webhook field, but this doesnt seem to work. Nothing gets sent and I'm assuming it's because it needs the `content` field in the payload with all of the necessary data. Can Discord be supported for this?

**Comment by kdolan** [comment]
The details of the match as well as the audio are made available in the webhook. You will need to massage this data to fit an external service such as discord. This can be done either by editing the code, adding a custom external program to push the data to discord in the format you need, or using an external service that can essentially forward the webhook to intergrate with other apps. IFTT comes to mind.

Here is where you could modify the JSON body of the webhook: https://github.com/kjdElectronics/fd-tone-notify/blob/main/notifiers/webhook.js#L11-L18

This is the function that posts the data: https://github.com/kjdElectronics/fd-tone-notify/blob/main/notifiers/webhook.js#L33-L50
