### ISSUE TITLE
pushbullet error

### ISSUE THREAD

**Issue by mattfox27** [kjdElectronics/fd-tone-notify#24]
Running windows, no matter what i do i get May-06-2024 22:30:17 crit : Push Bullet does not have an API Key. Notifications will not be sent

**Comment by kdolan** [comment]
This is simply telling you that you have not set a Pushbullet API Key. Notifications via Pushbullet will fail. This does not impact any other functionality.

**Comment by mattfox27** [comment]
But I did setup setup a Pushbullet account and put the key in the secrets.json file

**Comment by kdolan** [comment]
Please try the options here: https://github.com/kjdElectronics/fd-tone-notify?tab=readme-ov-file#environment-variables-and-secrets

Also check to make sure your secrets file is `config/secrets.json` (not template).
You can also try the `--force-secrets-file` in case this is being overridden by an env.
You can also try `--secrets-file <path>`  to explicitly provide a path to your secrets file. 

Also please provide the full startup output on --silly  log level.

**Comment by mattfox27** [comment]
It's weird I tried all that, it's in a folder on my c drive

C:\fire
Then c:\fire\config

I put the Pushbullet API key in between the "" in secrets.json and no matter what I try I get that Pushbullet error.  I just wanted to test it in window before setting it up in Linux.  It keeps saying it can't find the config file in logs.  Is there a particular directory structure In Windows it has to be?

**Comment by kdolan** [comment]
You need to maintain the directory structure. So put the exe in C;/fire then  start it. It will then populate the default config for you. Needs to look like this:
C:/fire
| - fd-tone-notify.exe
| - config/
|      - config.json
|      - secrets.json

You can also put secrets in a .env file in the same directory as fd-tone-notify.exe and that will pull env var overrides from there.

**Comment by mattfox27** [comment]
So wierd, yes I did all that, that is how my directory structure is and I renamed secrets.json file...shouli make a secrets.env file?

**Comment by kdolan** [comment]
In the same directory as the .exe create a ".env" file. In that file add one line:
`FD_PUSHBULLET_API_KEY=PASTE_API_KEY_HERE`
Then run the exe with the silly option and paste the output here.

**Comment by mattfox27** [comment]
OK I will try that when I get home.  In the secrets.json file do I have to remove any quotes?  or just add the API key in between the ""

**Comment by mattfox27** [comment]
OK I tried and it did not work with the env file, here are screenshots of the setup is there something missing or wrong?
![fd3](https://github.com/kjdElectronics/fd-tone-notify/assets/6801877/a4d7eded-d6cc-4d23-8352-85b374a795bf)
![fd2](https://github.com/kjdElectronics/fd-tone-notify/assets/6801877/c35b16a6-4853-43a7-af03-7908883c7bb6)
![FD](https://github.com/kjdElectronics/fd-tone-notify/assets/6801877/2e47a4b8-6aad-4a96-b632-7706c7eba3c6)

**Comment by kdolan** [comment]
Please start with --silly command line option

**Comment by mattfox27** [comment]
![silly](https://github.com/kjdElectronics/fd-tone-notify/assets/6801877/12a098f4-f2bc-4ef4-825c-b178a80d7417)

**Comment by mattfox27** [comment]
here is with test notifications
![notifications](https://github.com/kjdElectronics/fd-tone-notify/assets/6801877/9c4ed521-a97d-4d84-bef6-1e363b709a8c)

**Comment by mattfox27** [comment]
The pushbullet api is just the access token correct?

**Comment by kdolan** [comment]
Please start with --silly command line option

You should be starting this from command line and not by double clicking the exe

**Comment by mattfox27** [comment]
I do start with command line

**Comment by mattfox27** [comment]
> Please start with --silly command line option
> 
> You should be starting this from command line and not by double clicking the exe

I was starting from command line

**Comment by mattfox27** [comment]
![silly2](https://github.com/kjdElectronics/fd-tone-notify/assets/6801877/a4a66b2c-0f9c-497d-973c-8c6f50044bcd)

**Comment by kdolan** [comment]
This confirms the API Key is being set correctly from the secrets file. I will need to look into why the warning is being displayed prior to it being set.

**Comment by mattfox27** [comment]
Also when I do --test-notifications it says invalid API and fails

**Comment by mattfox27** [comment]
![Uploading 328720737-9c4ed521-a97d-4d84-bef6-1e363b709a8c.jpg…]()

**Comment by kdolan** [comment]
You will need to verify your API Key in Postman. Seems to be an issue with the API Key

**Comment by kdolan** [comment]
Please see #25
