### ISSUE TITLE
Windows version - error: unknown option

### ISSUE THREAD

**Issue by MrJordanRoth** [kjdElectronics/fd-tone-notify#26]
I have downloaded the Windows release and put it in a separate folder. I can open it manually by running the exe and running certain commands, but I can't run the command --tone-detector. I get an error saying: error: unknown option '--tone-detector'

**Comment by MrJordanRoth** [comment]
I also ran the fd-tone-notify.exe --help and do not see that command., II do see all-tone-detector

**Comment by kdolan** [comment]
Please provide screenshots of the command and error.

**Comment by MrJordanRoth** [comment]
![dBeXsBBs1h](https://github.com/kjdElectronics/fd-tone-notify/assets/71678703/f071b76d-193d-40d8-bc21-114fa11114e7)

I did find you can run --all-tone-detector

![cmd_E267dTIuwT](https://github.com/kjdElectronics/fd-tone-notify/assets/71678703/50b2aa2d-39e8-4e3e-8bf4-901a646ac979)

**Comment by kdolan** [comment]
What is the output of simply running it with no option?

**Comment by MrJordanRoth** [comment]
Screenshot of the error when running --tone-detector
![dBeXsBBs1h](https://github.com/kjdElectronics/fd-tone-notify/assets/71678703/8b9b6cf9-3831-43bc-8988-974791e9ba9b)

From the --help command:
![cmd_hOL4XTSoul](https://github.com/kjdElectronics/fd-tone-notify/assets/71678703/2355bd71-4bab-4206-9593-6d6cdc491631)

--all-tone-detector works

I also found a previous bug that has been closed in the Windows .exe file where the Pushbullet API key is not working correctly. Unsure if  I need to open a new ticket.

**Comment by MrJordanRoth** [comment]
Running with no options:
![cmd_3exUz3gFAb](https://github.com/kjdElectronics/fd-tone-notify/assets/71678703/76583db8-6977-4f9e-b687-5b2170191ae3)

**Comment by kdolan** [comment]
As indicated by the output of --help and the docs, `--tone-detector` is not a known command. Do you mean `--all-tone-detector`?
Re: The other bug (see other thread). Already responded.

Looks like everything is working correctly.

**Comment by MrJordanRoth** [comment]
You are correct, the documentation in the Quick Start is incorrect.
![image](https://github.com/kjdElectronics/fd-tone-notify/assets/71678703/2e92d9e2-88d9-42d9-9f15-537c9455d7d4)

**Comment by kdolan** [comment]
The documentation in the Quick Start is correct and was fixed two years ago in this commit. https://github.com/kjdElectronics/fd-tone-notify/commit/e65b0a9d0440e09ede489bcff737032cf8247fea

Make sure you are using the current main branch.
