### ISSUE TITLE
tone detector not working

### ISSUE THREAD

**Issue by ciuchs** [kjdElectronics/fd-tone-notify#7]
on initial run everything seemed fine but when i tried to run tone detector again it said command not found

 fd-tone-notify.exe --tone-detector --web-server

![fdn](https://user-images.githubusercontent.com/45048256/140812008-1f3c7882-087d-4e72-8ee2-63e2281e0ea0.png)

win 10

**Comment by kdolan** [comment]
Perhaps this was pointing to the wrong executable. Without more information there is not much troubleshooting that can be done.
